# Generated by Django 3.2.18 on 2023-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYSTEM', '0002_delete_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128, verbose_name='版本号')),
                ('router', models.CharField(max_length=64, verbose_name='路由器')),
                ('case', models.CharField(max_length=128, verbose_name='测试样例')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], verbose_name='状态')),
                ('msg', models.CharField(max_length=1024, verbose_name='日志信息')),
                ('elapsed', models.DateTimeField(verbose_name='运行时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
    ]
