# Generated by Django 3.2.18 on 2023-08-18 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SYSTEM', '0003_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.SmallIntegerField(choices=[(0, '版本烧录'), (1, '栈检查'), (2, '版本号'), (3, 'wifi连接'), (4, 'ble连接'), (5, '吞吐')], verbose_name='测试项')),
                ('sub_project', models.CharField(max_length=64, verbose_name='测试子项')),
                ('level', models.CharField(default='L0', max_length=16, verbose_name='用例等级')),
                ('preset_conditions', models.CharField(blank=True, max_length=256, null=True, verbose_name='预置条件')),
                ('step', models.TextField(blank=True, null=True, verbose_name='测试步骤')),
                ('expected_results', models.CharField(max_length=128, verbose_name='预期结果')),
                ('is_execute', models.BooleanField(verbose_name='是否执行')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='测试备注')),
                ('auto', models.BooleanField(verbose_name='自动化')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
        ),
    ]
