# Generated by Django 3.2.18 on 2023-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYSTEM', '0004_smoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Throughput',
        ),
        migrations.AddField(
            model_name='smoke',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
    ]
