# Generated by Django 3.2.18 on 2023-08-19 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SYSTEM', '0006_wifista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifista',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'L0'), (1, 'L1'), (2, 'L2'), (3, 'L3')], verbose_name='用例等级'),
        ),
        migrations.CreateModel(
            name='WifiAp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='用例编号')),
                ('category', models.SmallIntegerField(verbose_name='测试分类')),
                ('project', models.CharField(max_length=64, verbose_name='测试项')),
                ('sub_project', models.CharField(max_length=128, verbose_name='测试子项')),
                ('level', models.SmallIntegerField(choices=[(0, 'L0'), (1, 'L1'), (2, 'L2'), (3, 'L3')], verbose_name='用例等级')),
                ('preset_conditions', models.CharField(blank=True, max_length=256, null=True, verbose_name='预置条件')),
                ('step', models.TextField(blank=True, null=True, verbose_name='测试步骤')),
                ('expected_results', models.CharField(max_length=128, verbose_name='预期结果')),
                ('is_execute', models.BooleanField(verbose_name='是否执行')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='测试备注')),
                ('auto', models.BooleanField(verbose_name='自动化')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
        ),
    ]
