# Generated by Django 3.2.18 on 2023-08-19 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SYSTEM', '0010_wifift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiap',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'AP_STA'), (1, 'ASSOC'), (2, 'deauth'), (3, 'Gateway'), (4, 'IPERF'), (5, 'multi_sofap'), (6, 'QoS'), (7, 'STA&AP'), (8, 'STA_AP')], verbose_name='测试分类'),
        ),
        migrations.AlterField(
            model_name='wifidelay',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'ap&sta_ping'), (1, 'ap_ping'), (2, 'sta_assoc_rate'), (3, 'sta_assoc_time'), (4, 'sta_longping'), (5, 'sta_ping')], verbose_name='测试分类'),
        ),
        migrations.AlterField(
            model_name='wifift',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'ap&sta_Distance'), (1, 'ap_Distance'), (2, 'Complex'), (3, 'Distance'), (4, 'Normal'), (5, 'VeryComplex')], verbose_name='测试分类'),
        ),
        migrations.AlterField(
            model_name='wifista',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'ASSOC'), (1, 'fastconnect'), (2, 'IPERF'), (3, 'OFDMA'), (4, 'QoS'), (5, 'ROAMING')], verbose_name='测试分类'),
        ),
        migrations.AlterField(
            model_name='wifithroughput',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'AP__Normal'), (1, 'AP_Normal'), (2, 'ax 5个 sta吞吐'), (3, 'ax 8个 sta吞吐'), (4, 'bgn 5个 sta吞吐'), (5, 'bgn 8个 sta吞吐'), (6, 'softap连接AP 8sta吞吐'), (7, 'STA&AP_Normal'), (8, 'sta_VeryStrong'), (9, 'sta_Weak')], verbose_name='测试分类'),
        ),
        migrations.CreateModel(
            name='BleMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='用例编号')),
                ('category', models.SmallIntegerField(choices=[(0, 'BLE MESH BEARER'), (1, 'BLE MESH FEATURE'), (2, 'BLE MESH MODEL'), (3, '灯控（CLI指令）'), (4, '动态log level'), (5, '设备角色设置及feature组合')], verbose_name='测试分类')),
                ('project', models.CharField(max_length=64, verbose_name='测试项')),
                ('sub_project', models.CharField(max_length=128, verbose_name='测试子项')),
                ('level', models.SmallIntegerField(choices=[(0, 'L0'), (1, 'L1'), (2, 'L2'), (3, 'L3')], verbose_name='用例等级')),
                ('preset_conditions', models.CharField(blank=True, max_length=256, null=True, verbose_name='预置条件')),
                ('step', models.TextField(blank=True, null=True, verbose_name='测试步骤')),
                ('expected_results', models.CharField(max_length=128, verbose_name='预期结果')),
                ('is_execute', models.BooleanField(verbose_name='是否执行')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='测试备注')),
                ('auto', models.BooleanField(verbose_name='自动化')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
        ),
        migrations.CreateModel(
            name='Ble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='用例编号')),
                ('category', models.SmallIntegerField(choices=[(0, None), (1, 'CMD模式'), (2, 'Distance'), (3, '配网应用')], verbose_name='测试分类')),
                ('project', models.CharField(max_length=64, verbose_name='测试项')),
                ('sub_project', models.CharField(max_length=128, verbose_name='测试子项')),
                ('level', models.SmallIntegerField(choices=[(0, 'L0'), (1, 'L1'), (2, 'L2'), (3, 'L3')], verbose_name='用例等级')),
                ('preset_conditions', models.CharField(blank=True, max_length=256, null=True, verbose_name='预置条件')),
                ('step', models.TextField(blank=True, null=True, verbose_name='测试步骤')),
                ('expected_results', models.CharField(max_length=128, verbose_name='预期结果')),
                ('is_execute', models.BooleanField(verbose_name='是否执行')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='测试备注')),
                ('auto', models.BooleanField(verbose_name='自动化')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
        ),
    ]
