# Generated by Django 3.2.20 on 2023-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(verbose_name='编号')),
                ('band', models.CharField(max_length=64, verbose_name='品牌')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('chip', models.CharField(blank=True, max_length=128, null=True, verbose_name='芯片型号')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='详细信息')),
                ('status', models.SmallIntegerField(choices=[(1, '在线'), (2, '离线')], default='2', verbose_name='状态')),
            ],
            options={
                'verbose_name': '路由器',
                'verbose_name_plural': '路由器',
            },
        ),
    ]
