# Generated by Django 3.2.20 on 2023-08-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='number',
            field=models.CharField(max_length=32, verbose_name='编号'),
        ),
    ]
