# Generated by Django 3.2.20 on 2023-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_router_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='band',
            field=models.CharField(max_length=64, unique=True, verbose_name='品牌'),
        ),
    ]
