# Generated by Django 3.2.20 on 2023-08-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_router_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='status',
        ),
        migrations.AddField(
            model_name='router',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='带宽'),
        ),
        migrations.AddField(
            model_name='router',
            name='mode',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支持模式'),
        ),
        migrations.AddField(
            model_name='router',
            name='security',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='加密模式'),
        ),
    ]
