# Generated by Django 3.2.20 on 2023-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20230824_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支持带宽'),
        ),
        migrations.AlterField(
            model_name='router',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='router',
            name='security',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支持加密模式'),
        ),
    ]
