# Generated by Django 3.2.18 on 2023-08-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RVR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Router',
        ),
    ]
