# Generated by Django 3.2.20 on 2023-08-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throughput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128, verbose_name='版本号')),
                ('case', models.CharField(max_length=128, verbose_name='测试样例')),
                ('standard', models.FloatField(verbose_name='测试标准')),
                ('real', models.FloatField(verbose_name='实际测试')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], verbose_name='状态')),
                ('msg', models.CharField(max_length=1024, verbose_name='日志信息')),
                ('elapsed', models.DateTimeField(verbose_name='运行时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.router', to_field='name', verbose_name='路由器')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128, verbose_name='版本号')),
                ('case', models.CharField(max_length=128, verbose_name='测试样例')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], verbose_name='状态')),
                ('msg', models.CharField(max_length=1024, verbose_name='日志信息')),
                ('elapsed', models.DateTimeField(verbose_name='运行时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('environment', models.SmallIntegerField(blank=True, choices=[(4, '4楼'), (10, '10楼')], null=True, verbose_name='测试环境')),
                ('rssi', models.SmallIntegerField(blank=True, null=True, verbose_name='信号强度')),
                ('channel', models.SmallIntegerField(blank=True, null=True, verbose_name='信道序号')),
                ('bandwidth', models.SmallIntegerField(blank=True, choices=[(0, '20'), (1, '40')], null=True, verbose_name='信道带宽')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.router', to_field='name', verbose_name='路由器')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128, verbose_name='版本号')),
                ('case', models.CharField(max_length=128, verbose_name='测试样例')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], verbose_name='状态')),
                ('msg', models.CharField(max_length=1024, verbose_name='日志信息')),
                ('elapsed', models.DateTimeField(verbose_name='运行时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.router', to_field='name', verbose_name='路由器')),
            ],
        ),
    ]
