# Generated by Django 3.2.20 on 2023-08-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_router_band'),
        ('COMPATIBILITY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.router', to_field='band', verbose_name='路由器'),
        ),
        migrations.AlterField(
            model_name='test',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.router', to_field='band', verbose_name='路由器'),
        ),
        migrations.AlterField(
            model_name='throughput',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.router', to_field='band', verbose_name='路由器'),
        ),
    ]
