# Generated by Django 3.2.20 on 2023-08-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPATIBILITY', '0002_auto_20230823_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=128, null=True, verbose_name='版本号')),
                ('router', models.CharField(max_length=128, verbose_name='路由器')),
                ('case', models.CharField(max_length=128, verbose_name='测试样例')),
                ('category', models.SmallIntegerField(verbose_name='样例类型')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], verbose_name='状态')),
                ('msg', models.CharField(blank=True, max_length=1024, null=True, verbose_name='日志信息')),
                ('standard', models.FloatField(blank=True, null=True, verbose_name='测试标准')),
                ('real', models.FloatField(blank=True, null=True, verbose_name='实际测试')),
                ('elapsed', models.DateTimeField(verbose_name='运行时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('environment', models.SmallIntegerField(blank=True, choices=[(4, '4楼'), (10, '10楼')], null=True, verbose_name='测试环境')),
                ('rssi', models.SmallIntegerField(blank=True, null=True, verbose_name='信号强度')),
                ('channel', models.SmallIntegerField(blank=True, null=True, verbose_name='信道序号')),
                ('bandwidth', models.SmallIntegerField(blank=True, choices=[(0, '20M'), (1, '40M'), (3, '20/40M')], null=True, verbose_name='信道带宽')),
            ],
        ),
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=128, null=True, verbose_name='版本号')),
                ('router', models.CharField(max_length=128, verbose_name='路由器')),
                ('case', models.CharField(max_length=128, verbose_name='测试样例')),
                ('category', models.SmallIntegerField(verbose_name='样例类型')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], verbose_name='状态')),
                ('msg', models.CharField(blank=True, max_length=1024, null=True, verbose_name='日志信息')),
                ('standard', models.FloatField(blank=True, null=True, verbose_name='测试标准')),
                ('real', models.FloatField(blank=True, null=True, verbose_name='实际测试')),
                ('elapsed', models.DateTimeField(verbose_name='运行时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('environment', models.SmallIntegerField(blank=True, choices=[(4, '4楼'), (10, '10楼')], null=True, verbose_name='测试环境')),
                ('rssi', models.SmallIntegerField(blank=True, null=True, verbose_name='信号强度')),
                ('channel', models.SmallIntegerField(blank=True, null=True, verbose_name='信道序号')),
                ('bandwidth', models.SmallIntegerField(blank=True, choices=[(0, '20M'), (1, '40M'), (3, '20/40M')], null=True, verbose_name='信道带宽')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='router',
        ),
        migrations.RemoveField(
            model_name='throughput',
            name='router',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Throughput',
        ),
    ]
