# Generated by Django 3.2.20 on 2023-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPATIBILITY', '0003_auto_20230824_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '联网'), (1, '吞吐')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='iot',
            name='environment',
            field=models.SmallIntegerField(blank=True, choices=[(4, '4楼'), (10, '10楼')], null=True, verbose_name='测试楼层'),
        ),
        migrations.AlterField(
            model_name='tt',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '联网'), (1, '吞吐')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='tt',
            name='environment',
            field=models.SmallIntegerField(blank=True, choices=[(4, '4楼'), (10, '10楼')], null=True, verbose_name='测试楼层'),
        ),
    ]
