# Generated by Django 3.2.20 on 2023-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPATIBILITY', '0004_auto_20230824_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '联网'), (1, '加密'), (2, '吞吐')], verbose_name='类型'),
        ),
    ]
