# Generated by Django 3.2.20 on 2023-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPATIBILITY', '0005_alter_iot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='status',
            field=models.BooleanField(verbose_name='状态'),
        ),
    ]
