# Generated by Django 3.2.20 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPATIBILITY', '0006_alter_iot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='elapsed',
            field=models.TimeField(verbose_name='执行时间'),
        ),
    ]
